spring:
  cloud:
    stream:
      kafka:
        binder:
          autoAddPartitions: true
          minPartitionCount: 4

      bindings:
        filterSource-out-0:
          destination: raw_filter
          producer:
            partitionKeyExpression: payload.id

        categorySource-out-0:
          destination: raw_category
          producer:
            partitionKeyExpression: payload.id

        categoryProcessor-in-0:
          destination: raw_category
          group: myGroup

        categoryProcessor-out-0:
          destination: aggregate_category
          producer:
            partitionKeyExpression: payload.id

        filterProcessor-in-0:
          destination: raw_filter
          group: myGroup

        filterProcessor-out-0:
          destination: aggregate_category
          producer:
            partitionKeyExpression: payload.id

        categorySink-in-0:
          destination: aggregate_category
          group: myGroup
  data:
    mongodb:
      authentication-database: admin
      database: spring-cloud-stream-demo

