spring:
  cloud:
    stream:
      kafka:
        binder:
          autoAddPartitions: true
          minPartitionCount: 4

      bindings:
        filterGeneration-out-0:
          destination: raw_filter
          producer:
            partitionKeyExpression: payload.id

        categoryGeneration-out-0:
          destination: raw_category
          producer:
            partitionKeyExpression: payload.id

        categoryAggregation-in-0:
          destination: raw_category
          group: myGroup

        categoryAggregation-out-0:
          destination: aggregate_category
          producer:
            partitionKeyExpression: payload.id

        filterAggregation-in-0:
          destination: raw_filter
          group: myGroup

        filterAggregation-out-0:
          destination: aggregate_category
          producer:
            partitionKeyExpression: payload.id

        categorySink-in-0:
          destination: aggregate_category
          group: myGroup
  data:
    mongodb:
      authentication-database: admin
      database: spring-cloud-stream-demo

