spring:
  cloud:
    stream:
      bindings:
        processor-in-0:
          destination: raw_strings
          group: myGroup
        processor-out-0:
          destination: processed_strings
          group: myGroup